name: Build OpenWrt Docker x86-64 image 

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL: "https://github.com/henry-tujia/openwrt_docker/archive/refs/tags/1.0.tar.gz"
  REPOSITORY: henrytujia/openwrt
  TAG: 1.0.1

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
